#!/bin/bash
./migrate-to-preview.sh utqs-baitlc utexas-baitlc https://baitlc.utexas.edu >> migration-report.txt 2>&1
./migrate-to-preview.sh utqs-budget utexas-budget https://budget.utexas.edu >> migration-report.txt 2>&1
./migrate-to-preview.sh utqs-business-contracts utexas-business-contracts https://businesscontracts.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-chasp utexas-chasp https://chasp.lbj.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-child-family-research utexas-child-family-research https://childandfamilyresearch.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-commcouncil utexas-commcouncil https://commcouncil.utexas.org >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-compliance utexas-compliance https://compliance.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-covid-resource-guide utexas-whole-health https://covid.wholecommunities.utexas.edu >> migration-report.txt 2>&1
./migrate-to-preview.sh utqs-csrd utexas-csrd https://csrd.lbj.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-datacenters utexas-datacenters https://datacenters.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-dobie-paisano utexas-dobie-paisano https://dobiepaisano.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-faculty-council utexas-faculty-council https://facultycouncil.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-health-ipe utexas-health-ipe https://healthipe.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-impact-factory utexas-impact-factory https://theimpactfactory.org >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-internal-audits utexas-internal-audits https://audit.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-it-governance utexas-itlc https://itlc.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-kbh utexas-kbh https://kbhenergycenter.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-lbj-50 utexas-lbj-50 https://lbj50.org >> migration-report.txt 2>&1
./migrate-to-preview.sh utqs-lbj-wcs utexas-lbj-wcs https://lbjwcs.lbj.utexas.edu >> migration-report.txt 2>&1 
./migrate-to-preview.sh utqs-legal-affairs utexas-legal https://legal.utexas.edu >> migration-report.txt 2>&1
